project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_KEY
base_path: ./
preserve_hierarchy: true
commit_message: '[post] Update translations'
files:
-   source: pylavcogs_shared/**/messages.pot
    translation: /%original_path%/%locale%.po
