name: Crowdin - Upload strings
on:
    push:
        branches:
        -   master


jobs:
    deploy:
        if: github.repository == 'Drapersniper/PyLavCog-Shared'
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.8'
        -   name: Install dependencies
            run: |
                pip install redgettext==3.4.2
        -   name: Generate source files
            run: |
                python3.8 -m redgettext --command-docstrings --verbose --recursive .
        -   name: crowdin action
            uses: crowdin/github-action@1.4.10
            with:
                upload_translations: true
                download_translations: true
            env:
                CROWDIN_API_KEY: ${{ secrets.crowdin_token}}
                CROWDIN_PROJECT_ID: ${{ secrets.crowdin_identifier }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
